package com.aspose.cloud.sdk.cells.model;
import java.lang.String;

public class ChartModel {
               
	public String Name ;
	public String Type;
	public String Placement ;
	public int UpperLeftRow;
	public int Top ;
	public int UpperLeftColumn;
	public int Left ;
	public int LowerRightRow;
	public int Bottom ;
	public int LowerRightColumn ;
	public int Right ;
	public int Width;
	public int Height ;
	public int X;
	public int Y ;
	public String AlternativeText;
	public boolean IsGroup ;
	public boolean IsHidden ;
	public boolean IsLockAspectRatio;
	public boolean IsLocked ;
	public boolean IsPrintable;
	public boolean AutoScaling ;
	public int DepthPercent;
	public int Elevation ;
	public int FirstSliceAngle;
	public int GapDepth ;
	public int GapWidth;
	public short HeightPercent ;
	public boolean HidePivotFieldButtons;
	public boolean Is3D ;
	public boolean IsRectangularCornered ;
	public short Perspective;
	public String PivotSource ;
	public String PlotEmptyCellsType;
	public boolean PlotVisibleCells ;
	public String PrintSize;
	public boolean RightAngleAxes ;
	public int RotationAngle;
	public boolean ShowDataTable ;
	public boolean ShowLegend;
	public boolean SizeWithWindow ;
	public int Style;
	public boolean WallsAndGridlines2D ;
	public int ZOrderPosition;
}
