<?php

/**
 * @file
 * A module to import PDF to content
 */

use Aspose\Cloud\Common\AsposeApp;
use Aspose\Cloud\Common\Product;
use Aspose\Cloud\Words\Converter;

function aspose_pdf_exporter_init() {
    $path = drupal_get_path('module', 'aspose_pdf_exporter');

    spl_autoload_register('aspose_pdf_exporter_autoloader');
}

function aspose_pdf_exporter_autoloader($class) {
    $allowed_namespace = array('AsposeApp','Product','Folder','Converter','Utils','Extractor');
    $arr = explode('\\', $class);
    if(isset($arr[3])) {
        if( in_array( $arr[3] , $allowed_namespace)){
            include 'Aspose_Cloud_SDK_For_PHP-master/src/'. $arr[0] . '/' . $arr[1] . '/' .$arr[2] . '/' . $arr[3] . '.php';
        }
    } else if (isset($arr['3'])) {
        if( in_array( $arr['3'] , $allowed_namespace)){
            include 'Aspose_Cloud_SDK_For_PHP-master/src/'. $arr[0] . '/' . $arr[1] . '/' .$arr[2] . '/' . $arr[3] . '.php';
        }
    }
}

function aspose_pdf_exporter_menu () {
    $items['admin/aspose_pdf_exporter/download_file'] = array(
        'title' => 'Download exported PDF File',
        'file' => 'aspose_pdf_exporter.module',
        'page callback' => 'aspose_pdf_exporter_download_converted_file',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    $items['admin/settings/aspose-pdf-exporter-settings'] = array(
        'title' => 'Aspose PDF Exporter Settings',
        'description' => t('API Configurations for PDF Exporter'),
        'page callback' => 'drupal_get_form', // assuming that you want to use a form
        'page arguments' => array('_aspose_pdf_exporter_form_builder'),
        'access callback' => 'user_access',
        'access arguments' => array('administer content types'), // or use hook_perm() to make your own
        'type' => MENU_LOCAL_ACTION,
    );

    return $items;
}

function _aspose_pdf_exporter_form_builder(){
    $form['aspose_pdf_exporter_api_sid'] = array(
        '#type' => 'textfield',
        '#title' => t('APP SID'),
        '#default_value' => variable_get('_aspose_pdf_exporter_api_sid_value') //false by default
    );

    $form['aspose_pdf_exporter_api_key'] = array(
        '#type' => 'textfield',
        '#title' => t('APP KEY'),
        '#default_value' => variable_get('_aspose_pdf_exporter_api_key_value') //false by default
    );

    // saves and executes a submission callback, see $form["#submit"] for that
    $form['save'] = array(
        '#type' => 'submit',
        '#value' => t('Save'),
        '#executes_submit_callback' => true
    );

    $form['#submit'] = array(
        '_aspose_pdf_exporter_form_submit_special_fuction_name'
    );

    return $form;
}

function _aspose_pdf_exporter_form_submit_special_fuction_name($form, &$form_state){
    //check $form_state['values'] and use this below line to set the value
    variable_set('_aspose_pdf_exporter_api_sid_value', $_POST['aspose_pdf_exporter_api_sid']);
    variable_set('_aspose_pdf_exporter_api_key_value', $_POST['aspose_pdf_exporter_api_key']);
}

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function aspose_pdf_exporter_help($path, $arg) {
    switch ($path) {
        case "admin/help#aspose_pdf_exporter":
            return '<p>' . t("I am testing from help hook") . '</p>';
            break;
    }
}

/**
 * Implements hook_block_info().
 */
function aspose_pdf_exporter_block_info() {
    $blocks['aspose_pdf_exporter'] = array(
        // The name that will appear in the block list.
        'info' => t('Aspose PDF Exporter from Block Info Hook'),
        // Default setting.
        //'cache' => DRUPAL_CACHE_PER_ROLE,
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
}

function aspose_pdf_exporter_view() {
    $blocks['aspose_pdf_exporter'] = array(
        // The name that will appear in the block list.
        'info' => t('Aspose PDF Exporter from Block View'),
        // Default setting.
        //'cache' => DRUPAL_CACHE_PER_ROLE,
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
}

function aspose_pdf_exporter_node_operations() {
    $operations = array(
        'aspose_pdf_exporter' => array(
            'label' => t('Aspose Export to PDF'),
            'callback' => 'aspose_pdf_exporter_export_pdfs',
        )
    );
    return $operations;
}

function aspose_pdf_exporter_export_pdfs($selected_nodes) {
    try {
        foreach($selected_nodes as $node_id) {
            // load node
            $node_data = node_load($node_id);

            // Extract content
            $node_title = $node_data->title;
            $node_content = $node_data->body['und'][0]['safe_value'];

            // Update node contents array
            $node_contents[$node_title] = $node_content;
        }


        if(is_array($node_contents) && !empty($node_contents)) {
            $file_name = _aspose_pdf_exporter_convert_array_to_html($node_contents);
        } else {
            return false;
        }

        $upload_dir = drupal_get_path('module', 'aspose_pdf_exporter');
        $upload_path = $upload_dir . '/uploads/';
        /*
         *  Assign appSID and appKey of your Aspose App
         */
        AsposeApp::$appSID = variable_get('_aspose_pdf_exporter_api_sid_value');
        AsposeApp::$appKey = variable_get('_aspose_pdf_exporter_api_key_value');
        AsposeApp::$outPutLocation = $upload_path;
        /*
         * Assign Base Product URL
         */
        Product::$baseProductUri = 'http://api.aspose.com/v1.1';

        $func = new Converter('output.pdf');
        $func->convertLocalFile($file_name,'','pdf');

        $file_to_download = drupal_realpath($upload_path . 'output.pdf');

        global $base_url;
        $success_message = 'Post exported. <a href="' . $base_url . '/admin/aspose_pdf_exporter/download_file?file=' . $file_to_download . '">Click Here</a> to download the pdf file.';

        drupal_set_message(t($success_message), 'status');
    } catch(Exception $someExp) {
        drupal_set_message(t($someExp->getMessage()), 'error');
    }
}

function aspose_pdf_exporter_download_converted_file() {
    $file = $_GET['file'];
    
    $file_arr = explode('/',$file);
    $file_name = $file_arr[count($file_arr) - 1];

    header ("Content-type: octet/stream");
    header ("Content-disposition: attachment; filename=".$file_name.";");
    header("Content-Length: ".filesize($file));

    readfile($file);
    exit;
}

function _aspose_pdf_exporter_convert_array_to_html($node_contents){
    $upload_dir = drupal_get_path('module', 'aspose_pdf_exporter');
    $upload_path = $upload_dir . '/uploads/';
    $filename = 'output.html';

    $output_string = <<<EOD
<!DOCTYPE html>
<html>
    <head>
        <title></title>
    </head>
    <body>
EOD;

    foreach($node_contents as $node_title => $node_content) {
        $output_string .= <<<EOD
        <h1> {$node_title} </h1>
        <p> {$node_content} </p>
        <hr />
EOD;
    }
    $output_string .= <<<EOD
</body>
</html>
EOD;

    file_put_contents($upload_path . $filename,$output_string);

    return $upload_path . $filename;
}